### ISSUE TITLE
How to add Interceptor 

### ISSUE THREAD

**Issue by altafShaikh1717** [salihagic/rest_api_client#10]
I want to add Interceptor in each request. How I can add using this package.

**Comment by altafShaikh1717** [comment]
added parameter for Interceptor 
repo(fork) https://github.com/altafShaikh1717/rest_api_client

**Comment by salihagic** [comment]
Hi @altafShaikh1717, thanks for opening this issue. It is certainly a useful option and while fixing another issue I added your suggestion also. You can find the new parameter `List<Interceptor> interceptors = const []` in RestApiClient's constructor in version:  2.1.4
