### ISSUE TITLE
More info on Error/Exception handling

### ISSUE THREAD

**Issue by eggzotic** [salihagic/rest_api_client#11]
Could you provide more examples/description on how to perform tidy exception handling? For example, I see the exceptionHandler.exceptions stream - which looks like a useful idea. However it only accepts subclasses of BaseException - so, for example, the rest API client property .exception cannot be added into the stream without first being re-constructed into a BaseException. I suppose I would find it more useful if the DioError was available from that stream directly, as it seems to contain the info I'd like to react-to/present.

**Comment by salihagic** [comment]
Hi @eggzotic, thanks for opening this issue and sorry for the late response.

Here is a little tip, what I often do in my projects for handling error cases and displaying error messages for bad requests:

I create global error handler Cubit (or Notifier or anything else that you use for state management), inject restApiClient and subscribe to it's exception handler stream and display these messages globally via Snackbar or Toast messages.

This way you guide error messages displaying away from the main flow and can focus on the main flow without handling this in every http call you make.

Code example in Cubit:
```
class ErrorHandlerCubit extends Cubit<ErrorHandlerState> {
  final RestApiClient restApiClient;
  late StreamSubscription _restApiClientSubscription;

  ErrorHandlerCubit({
    required this.restApiClient,
  }) : super(ErrorHandlerState(status: ErrorHandlerStateStatus.clean)) {
    _restApiClientSubscription = restApiClient.exceptionHandler.exceptions.stream.listen((exception) {
      addNewException(exception);
    });
  }

  Future<void> addNewException(BaseException exception) async {
    emit(
      ErrorHandlerState(
        status: ErrorHandlerStateStatus.dirty,
        exception: exception,
      ),
    );
  }

  @override
  Future<void> close() {
    _restApiClientSubscription.cancel();

    return super.close();
  }
}
```

UI (widget) that listens state changes:
```
class ErrorHandlerAppWidgetListener extends StatelessWidget {
  final Widget child;

  const ErrorHandlerAppWidgetListener({
    super.key,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    return BlocListener<ErrorHandlerCubit, ErrorHandlerState>(
      listener: (context, errorHandlerState) {
        if (errorHandlerState.showMessage) {
          toast.showExceptionMessage(errorHandlerState.exception!);
        }
      },
      child: child,
    );
  }
}
```

On the top of my app:
```
child: MaterialApp.router(
  builder: (context, child) {
    return ErrorHandlerAppWidgetListener(
      child: child!,
    );
  },
  routerConfig: appRouter,
),
```

Additionally you can provide a parser for error messages in RestApiClientImpl initial configuration (when creating an instance of your restApiClient object):
```
final RestApiClient restApiClient = RestApiClientImpl(
  //...
  exceptionOptions: ExceptionOptions(
    resolveValidationErrorsMap: (response) {
      if (response != null && response.data != null && response.data['code'] != null) {
        return {
          'ERROR': [ErrorMessagesMapper.map(response.data['code'])],
        };
      }

      return {};
    },
  ),
  // ...
);
```

_You can also handle exceptions directly in your repo method call where you get restApiClient's result. You can access result.exception or other data like statusCode or data if there is any._

**Comment by eggzotic** [comment]
Thanks for that. Yes I think I did make something like this since that was so long ago and this idea eventually dawned on me. I'd kind of forgotten I'd asked this :-) Cheers.
