### ISSUE TITLE
We should set timeout delay in the options

### ISSUE THREAD

**Issue by ec-ecss** [salihagic/rest_api_client#12]
Hello
I think timeout waiting time is quite long, can we acces the dio timeout option via rest_api_client call ?

**Comment by eggzotic** [comment]
We can add timeout to each get/post/etc call like this:
```
await _apiClient.get(someApiPath).timeout(Duration(seconds: 2));
```

**Comment by ec-ecss** [comment]
Thank you for the tip ! But it would be more clear and trivial to use the RestApiClientOptions when construct the RestApiClient service
