### ISSUE TITLE
RestApiClientOptions overrideBadCertificate not working?

### ISSUE THREAD

**Issue by eggzotic** [salihagic/rest_api_client#14]
It seems that

```
RestApiClient(
     options: RestApiClientOptions(
        overrideBadCertificate: true,
     ),
...
),

```
makes no difference (`true` vs `false`) - whenever attempting a call (e.g. `POST`) to an SSL-enabled API with a self-signed certificate, the browser rejects it with `net::ERR_CERT_INVALID`. The only work around is to have the API present a cert that the browser has previously accepted - e.g. if the app is loaded from the same web-server (e.g. NGINX acting as front-end server for both the app and the API) - and the user has forced the browser to accept it (e.g. Chrome - by typing `thisisunsafe` blindly), then the app will proceed to make API calls as per the code.

During app-dev/debug, the workaround is to serve the API via plain HTTP and disable CORS in the browser etc.

**Comment by salihagic** [comment]
This issue should be fine in the latest version, please upgrade and test. Closing for now.
