### ISSUE TITLE
Dio vulnerability: CRLF injection if the attacker controls the HTTP method string

### ISSUE THREAD

**Issue by sebjamesmelon** [salihagic/rest_api_client#15]
## Problem:

The dio package 4.0.0 for Dart allows CRLF injection if the attacker controls the HTTP method string
https://github.com/advisories/GHSA-9324-jv53-9cc8

The vulnerability has been resolved by https://github.com/cfug/dio/commit/927f79e93ba39f3c3a12c190624a55653d577984, and included since v5.0.0.

## Solution:

Upgrade the Dio dependency to at least 5.0.0. 

**Note that 5.0.0 does introduce breaking changes.**

**Comment by salihagic** [comment]
Hi @sebjamesmelon, thanks for opening this issue, I have upgraded the dependency of dio package. Please open more issues if there is something else that you think should be fixed.
