### ISSUE TITLE
Bad response data is not fetching

### ISSUE THREAD

**Issue by berkeugur** [salihagic/rest_api_client#18]
<img width="332" alt="Screenshot 2024-05-07 at 18 37 35" src="https://github.com/salihagic/rest_api_client/assets/63670094/84780b70-f9f8-4039-b71b-c18ad5d19188">

i have status code 400 body like this
{
       success: false,
       data: null,
       error: "user not found",
}
but response.data is 

<img width="279" alt="Screenshot 2024-05-07 at 18 39 31" src="https://github.com/salihagic/rest_api_client/assets/63670094/94384af3-32d8-449a-91d9-187188eea6d7">

response.isError is returned true
(response as NetworkResult).data returned null
i need get "user not found" bad response body message
How can i get? please help me

**Comment by salihagic** [comment]
Hi @berkeugur, thank you for reporting that issue. That makes sense and I fixed it in the new rest_api_client version, you can upgrade to 2.2.20 and try it now, I tested it and it seams to work fine.

This code:
```
final result = await restApiClient.post(
  'https://app.biyuk.com.tr/auth/login',
  data: {
    'email': 'example@email.com',
    'password': 'password',
  },
);

print('DATA: ${result.data}');
```


Produces this log:
```
╔ Body 
╟ email: example@email.com
╟ password: password
╚══════════════════════════════════════════════════════════════════════════════════════════╝
║ {email: example@email.com, password: password}

╔╣ DioError ║ Status: 400 Bad Request
║  https://app.biyuk.com.tr/auth/login
╚══════════════════════════════════════════════════════════════════════════════════════════╝
╔ DioExceptionType.badResponse
║    {
║         success: false,
║         data: null,
║         error: "Kullanıcı bulunamadı."
║    }
╚══════════════════════════════════════════════════════════════════════════════════════════╝

EXCEPTION: {success: false, data: null, error: Kullanıcı bulunamadı.}
```

Please try it out, hope it works. If there are any other issues please comment or open separate issue.

**Comment by salihagic** [comment]
Here is a little tip, what I often do in my projects for handling error cases and displaying error messages for bad requests:

I create global error handler Cubit (or Notifier or anything else that you use for state management), inject restApiClient and subscribe to it's exception handler stream and display these messages globally via Snackbar or Toast messages.

This way you guide error messages displaying away from the main flow and can focus on the main flow without handling this in every http call you make.

Code example in Cubit:
```
class ErrorHandlerCubit extends Cubit<ErrorHandlerState> {
  final RestApiClient restApiClient;
  late StreamSubscription _restApiClientSubscription;

  ErrorHandlerCubit({
    required this.restApiClient,
  }) : super(ErrorHandlerState(status: ErrorHandlerStateStatus.clean)) {
    _restApiClientSubscription = restApiClient.exceptionHandler.exceptions.stream.listen((exception) {
      addNewException(exception);
    });
  }

  Future<void> addNewException(BaseException exception) async {
    emit(
      ErrorHandlerState(
        status: ErrorHandlerStateStatus.dirty,
        exception: exception,
      ),
    );
  }

  @override
  Future<void> close() {
    _restApiClientSubscription.cancel();

    return super.close();
  }
}
```

UI (widget) that listens state changes:
```
class ErrorHandlerAppWidgetListener extends StatelessWidget {
  final Widget child;

  const ErrorHandlerAppWidgetListener({
    super.key,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    return BlocListener<ErrorHandlerCubit, ErrorHandlerState>(
      listener: (context, errorHandlerState) {
        if (errorHandlerState.showMessage) {
          toast.showExceptionMessage(errorHandlerState.exception!);
        }
      },
      child: child,
    );
  }
}
```

On the top of my app:
```
child: MaterialApp.router(
  builder: (context, child) {
    return ErrorHandlerAppWidgetListener(
      child: child!,
    );
  },
  routerConfig: appRouter,
),
```

Additionally you can provide a parser for error messages in RestApiClientImpl initial configuration (when creating an instance of your restApiClient object):
```
final RestApiClient restApiClient = RestApiClientImpl(
  //...
  exceptionOptions: ExceptionOptions(
    resolveValidationErrorsMap: (response) {
      if (response != null && response.data != null && response.data['code'] != null) {
        return {
          'ERROR': [ErrorMessagesMapper.map(response.data['code'])],
        };
      }

      return {};
    },
  ),
  // ...
);
```

**Comment by berkeugur** [comment]
Thank you for your contribution! It really helped me out. You're clearly a skilled coder. I appreciate it a lot. Could you provide additional information about the ErrorHandlerState and ErrorHandlerStateStatus classes?
