### ISSUE TITLE
Unhandled exception related to shared_preferences

### ISSUE THREAD

**Issue by ggabrovski** [salihagic/rest_api_client#2]
I have a problem in case when my app use shared_preferences library to store other data that are not related to rest_api_client. 
In my case I store some `double` data in shared_preferences, but this case an error in the storage_repository library -  method  `_copyDataFromLegacyStorage` because it expect all data to be `string`:
https://github.com/salihagic/storage_repository/blob/444d99337f834d5f552335143344ffb413146dbe/lib/implementations/storage_repository.dart#L35

The second problem is removing of all this data:
https://github.com/salihagic/storage_repository/blob/444d99337f834d5f552335143344ffb413146dbe/lib/implementations/storage_repository.dart#L37

Also it will be great if the cachedStorageRepository is lazy instantiate, because it's not always used.

I don't know if here is the right place to address this problem or it need to be made it in salihagic/storage_repository. Because I suggest that this call to `_copyDataFromLegacyStorage` is used for some BC issue.

**Comment by salihagic** [comment]
Hi @ggabrovski, thank you for opening this issue. 
This is a missed edge case which will be fixed immediately. Update is comming soon.

Also good suggestion for lazy instantiation of cachedStorageRepository.

**Comment by ggabrovski** [comment]
Hi @salihagic,
thanks for the fast reply and for the great package.

**Comment by salihagic** [comment]
This issue is considered closed with [rest_api_client](https://pub.dev/packages/rest_api_client) version 1.0.23
