### ISSUE TITLE
Access to JWT Token 

### ISSUE THREAD

**Issue by ggabrovski** [salihagic/rest_api_client#3]
In the new version 1.23 storageRepository is private and there is no way to get the JWT token if you need to decode it. 
In the old versions I can make something like this:

`
final jwt = await restApiClient.storageRepository.get(RestApiClientKeys.jwt);  
`

It will be great if in the next version we can have some helper method to get the value saved under a given key. Thanks!

**Comment by salihagic** [comment]
Hi @ggabrovski 
Thanks for opening this issue and sorry for the late reply.
You can find this feature implemented in rest_api_client version 1.1.10 via jwt and refreshToken getters on IRestApiClient.
