### ISSUE TITLE
Option to disable logging of cache on init

### ISSUE THREAD

**Issue by andreap7** [salihagic/rest_api_client#5]
Currently it is not possible to disable logging of the storage repository data and the cached storage repository data. It would be better if we could disable it through the LoggingOptions.

![image](https://user-images.githubusercontent.com/61591490/157451913-0efbc1c3-636b-44d5-85d7-0c24764f890f.png)

**Comment by salihagic** [comment]
Thanks for submitting this issue, I will add it soon.
