### ISSUE TITLE
jwt required in body of refreshtokenendpoint data

### ISSUE THREAD

**Issue by eggzotic** [salihagic/rest_api_client#9]
Currently using in my flutter project's `pubspec.yaml` file:
`  rest_api_client: ^2.1.3
`
When the auth token (jwt) expires, the post to authOptions.refreshTokenEndpoint on line 119, of the file `lib/implementations/auth_handler.dart` fails with "Status: 400 BAD REQUEST" and "message: "Invalid parameters"" as the data contains only the `refreshToken`. At least for the API I am using, we must also include a field in the data with the JWT like this:
`            'token': await _storage.get(RestApiClientKeys.jwt),
`
Can we add that? Maybe it needs to be an option at the time we call the AuthOptions constructor to include the key-name for that field?

**Comment by salihagic** [comment]
Hi @eggzotic, thanks for reporting this issue, I have received a similar request recently and added following to AuthOptions:
```
  final dynamic Function(String jwt, String refreshToken)? refreshTokenBodyBuilder;
  final Map<String, dynamic>? Function(String jwt, String refreshToken)? refreshTokenHeadersBuilder;
```

So now you can override the part that fits your requirements. Please follow up with a response if this fixes your issue, and any other bug please report another issue.

This fix will is now available in version: 2.1.4

**Comment by eggzotic** [comment]
Hey thanks for the new version with this feature included!

It works perfectly on Windows, but for some reason it fails on Mac OS X - as-in on Mac OS the exact same code in `refreshTokenBodyBuilder`, hitting the same API, receives an HTTP 403.

FYI I'm using this in authOptions:
```
        refreshTokenBodyBuilder: (jwt, refreshToken) =>
            {AuthKey.token.name: jwt, AuthKey.refreshToken.name: refreshToken},

```
where AuthKey is an enum:
```
enum AuthKey {
  // used in requests only
  username,
  password,
  // used in both requests and responses
  token,
  refreshToken;

  factory AuthKey.fromName(String name) =>
      AuthKey.values.firstWhere((key) => key.name == name);
}
```

**Comment by salihagic** [comment]
Hi @eggzotic 
Are you building a desktop app?
Have you tried hardcoding a string there(for parameter names), just for test purposes?

**Comment by eggzotic** [comment]
Yes, I tried hardcoding the values etc - always failed with 403. Then just today I happened to run the same code on the Windows machine and realised that the token-refreshes were "just working". So I am guessing that Mac OS might be doing something strange. I will try to re-create a minimal example for debugging.

**Comment by eggzotic** [comment]
Apologies - having just upgraded Flutter & packages in my project, on Mac OS - the token-refresh is now working perfectly. So all is well. Thx again for this very cool package!

**Comment by salihagic** [comment]
Great, closing this issue now.
